title: Vinyl Lens Chrome Extension
description: Chrome拡張機能「Vinyl Lens」のサポートページ / Support page for Vinyl Lens Chrome Extension
theme: jekyll-theme-minimal
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed

# GitHub Pages settings
github:
  repository_name: chrome-extension-vinyl-lens
  repository_url: https://github.com/junyan21/chrome-extension-vinyl-lens
  owner_name: junyan21
  
# Site settings
lang: ja
baseurl: "/chrome-extension-vinyl-lens"
url: "https://junyan21.github.io"

# Navigation
navigation:
  - title: Home
    url: /
  - title: GitHub
    url: https://github.com/junyan21/chrome-extension-vinyl-lens